/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantautomation;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Alejandro
 */
public class RestaurantLayout extends JFrame {

    /**
     * Creates new form RestaurantLayout
     */
    public RestaurantLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablesPanel = new javax.swing.JPanel();
        table_1_button = new javax.swing.JToggleButton();
        table_2_button = new javax.swing.JToggleButton();
        table_3_button = new javax.swing.JToggleButton();
        table_4_button = new javax.swing.JToggleButton();
        table_5_button = new javax.swing.JToggleButton();
        table_6_button = new javax.swing.JToggleButton();
        table_7_button = new javax.swing.JToggleButton();
        table_8_button = new javax.swing.JToggleButton();
        detailPanel = new javax.swing.JPanel();
        tableStatusPanel = new javax.swing.JPanel();
        freeTablePanel = new javax.swing.JPanel();
        freeStatusLabel = new javax.swing.JLabel();
        dirtyTablePanel = new javax.swing.JPanel();
        dirtyStatusLabel = new javax.swing.JLabel();
        usedTablePanel = new javax.swing.JPanel();
        occupiedStatusLabel = new javax.swing.JLabel();
        tableStatusLabel = new javax.swing.JLabel();
        stdLabel = new javax.swing.JLabel();
        stdPanel = new javax.swing.JPanel();
        stdTableName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Table Availability");
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        tablesPanel.setBackground(new java.awt.Color(255, 255, 255));

        table_1_button.setBackground(new java.awt.Color(153, 255, 153));
        table_1_button.setText("Table 1");
        table_1_button.setToolTipText("");
        table_1_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_1_buttonActionPerformed(evt);
            }
        });

        table_2_button.setBackground(new java.awt.Color(153, 255, 153));
        table_2_button.setText("Table 2");
        table_2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_2_buttonActionPerformed(evt);
            }
        });

        table_3_button.setBackground(new java.awt.Color(153, 255, 153));
        table_3_button.setText("Table 3");
        table_3_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_3_buttonActionPerformed(evt);
            }
        });

        table_4_button.setBackground(new java.awt.Color(153, 255, 153));
        table_4_button.setText("Table 4");
        table_4_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_4_buttonActionPerformed(evt);
            }
        });

        table_5_button.setBackground(new java.awt.Color(153, 255, 153));
        table_5_button.setText("Table 5");
        table_5_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_5_buttonActionPerformed(evt);
            }
        });

        table_6_button.setBackground(new java.awt.Color(153, 255, 153));
        table_6_button.setText("Table 6");
        table_6_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_6_buttonActionPerformed(evt);
            }
        });

        table_7_button.setBackground(new java.awt.Color(153, 255, 153));
        table_7_button.setText("Table 7");
        table_7_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_7_buttonActionPerformed(evt);
            }
        });

        table_8_button.setBackground(new java.awt.Color(153, 255, 153));
        table_8_button.setText("Table 8");
        table_8_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_8_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablesPanelLayout = new javax.swing.GroupLayout(tablesPanel);
        tablesPanel.setLayout(tablesPanelLayout);
        tablesPanelLayout.setHorizontalGroup(
            tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table_1_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table_5_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(table_2_button, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(table_6_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(table_3_button, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(table_7_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(table_4_button, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(table_8_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        tablesPanelLayout.setVerticalGroup(
            tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table_4_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table_3_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table_2_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table_1_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(table_5_button, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(table_6_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(table_7_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(table_8_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        detailPanel.setBackground(new java.awt.Color(50, 50, 50));

        tableStatusPanel.setBackground(new java.awt.Color(100, 100, 100));

        freeTablePanel.setBackground(new java.awt.Color(153, 255, 153));

        freeStatusLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        freeStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        freeStatusLabel.setText("Free");

        javax.swing.GroupLayout freeTablePanelLayout = new javax.swing.GroupLayout(freeTablePanel);
        freeTablePanel.setLayout(freeTablePanelLayout);
        freeTablePanelLayout.setHorizontalGroup(
            freeTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(freeStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        freeTablePanelLayout.setVerticalGroup(
            freeTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(freeStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        dirtyTablePanel.setBackground(new java.awt.Color(255, 255, 0));

        dirtyStatusLabel.setFont(new java.awt.Font("Segoe WP Light", 0, 24)); // NOI18N
        dirtyStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dirtyStatusLabel.setText("Dirty");

        javax.swing.GroupLayout dirtyTablePanelLayout = new javax.swing.GroupLayout(dirtyTablePanel);
        dirtyTablePanel.setLayout(dirtyTablePanelLayout);
        dirtyTablePanelLayout.setHorizontalGroup(
            dirtyTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dirtyStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dirtyTablePanelLayout.setVerticalGroup(
            dirtyTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dirtyStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        usedTablePanel.setBackground(new java.awt.Color(255, 153, 153));

        occupiedStatusLabel.setFont(new java.awt.Font("Segoe WP Light", 0, 24)); // NOI18N
        occupiedStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        occupiedStatusLabel.setText("Occupied");

        javax.swing.GroupLayout usedTablePanelLayout = new javax.swing.GroupLayout(usedTablePanel);
        usedTablePanel.setLayout(usedTablePanelLayout);
        usedTablePanelLayout.setHorizontalGroup(
            usedTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(occupiedStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        usedTablePanelLayout.setVerticalGroup(
            usedTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(occupiedStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tableStatusPanelLayout = new javax.swing.GroupLayout(tableStatusPanel);
        tableStatusPanel.setLayout(tableStatusPanelLayout);
        tableStatusPanelLayout.setHorizontalGroup(
            tableStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(freeTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dirtyTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usedTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tableStatusPanelLayout.setVerticalGroup(
            tableStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(freeTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dirtyTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usedTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableStatusLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        tableStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        tableStatusLabel.setText("Table Status");

        stdLabel.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 18)); // NOI18N
        stdLabel.setForeground(new java.awt.Color(255, 255, 255));
        stdLabel.setText("Selected Table Detail");

        stdPanel.setBackground(new java.awt.Color(100, 100, 100));

        stdTableName.setBackground(new java.awt.Color(255, 255, 255));
        stdTableName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        stdTableName.setForeground(new java.awt.Color(255, 255, 255));
        stdTableName.setText("No Table");

        javax.swing.GroupLayout stdPanelLayout = new javax.swing.GroupLayout(stdPanel);
        stdPanel.setLayout(stdPanelLayout);
        stdPanelLayout.setHorizontalGroup(
            stdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stdTableName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        stdPanelLayout.setVerticalGroup(
            stdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stdTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        if (table_1_button.isSelected()) {
            stdTableName.setText(table_1_button.getText());
        } else if (table_2_button.isSelected()) {
            stdTableName.setText(table_2_button.getText());
        }

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableStatusPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableStatusLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addContainerGap())
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_1_buttonActionPerformed
        // TODO add your handling code here:

        // Delselects all the other buttons, ensures only a single button is selected
        if (table_2_button.isSelected()) {
            table_2_button.setSelected(false);
        }
        if (table_3_button.isSelected()) {
            table_3_button.setSelected(false);
        }
        if (table_4_button.isSelected()) {
            table_4_button.setSelected(false);
        }
        if (table_5_button.isSelected()) {
            table_5_button.setSelected(false);
        }
        if (table_6_button.isSelected()) {
            table_6_button.setSelected(false);
        }
        if (table_7_button.isSelected()) {
            table_7_button.setSelected(false);
        }
        if (table_8_button.isSelected()) {
            table_8_button.setSelected(false);
        }
    }//GEN-LAST:event_table_1_buttonActionPerformed

    private void table_2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_2_buttonActionPerformed
        // TODO add your handling code here:

        // Delselects all the other buttons, ensures only a single button is selected
        if (table_1_button.isSelected()) {
            table_1_button.setSelected(false);
        }
        if (table_3_button.isSelected()) {
            table_3_button.setSelected(false);
        }
        if (table_4_button.isSelected()) {
            table_4_button.setSelected(false);
        }
        if (table_5_button.isSelected()) {
            table_5_button.setSelected(false);
        }
        if (table_6_button.isSelected()) {
            table_6_button.setSelected(false);
        }
        if (table_7_button.isSelected()) {
            table_7_button.setSelected(false);
        }
        if (table_8_button.isSelected()) {
            table_8_button.setSelected(false);
        }
    }//GEN-LAST:event_table_2_buttonActionPerformed

    private void table_3_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_3_buttonActionPerformed
        // TODO add your handling code here:

        // Delselects all the other buttons, ensures only a single button is selected
        if (table_1_button.isSelected()) {
            table_1_button.setSelected(false);
        }
        if (table_2_button.isSelected()) {
            table_2_button.setSelected(false);
        }
        if (table_4_button.isSelected()) {
            table_4_button.setSelected(false);
        }
        if (table_5_button.isSelected()) {
            table_5_button.setSelected(false);
        }
        if (table_6_button.isSelected()) {
            table_6_button.setSelected(false);
        }
        if (table_7_button.isSelected()) {
            table_7_button.setSelected(false);
        }
        if (table_8_button.isSelected()) {
            table_8_button.setSelected(false);
        }
    }//GEN-LAST:event_table_3_buttonActionPerformed

    private void table_4_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_4_buttonActionPerformed
        // TODO add your handling code here:

        // Delselects all the other buttons, ensures only a single button is selected
        if (table_1_button.isSelected()) {
            table_1_button.setSelected(false);
        }
        if (table_2_button.isSelected()) {
            table_2_button.setSelected(false);
        }
        if (table_3_button.isSelected()) {
            table_3_button.setSelected(false);
        }
        if (table_5_button.isSelected()) {
            table_5_button.setSelected(false);
        }
        if (table_6_button.isSelected()) {
            table_6_button.setSelected(false);
        }
        if (table_7_button.isSelected()) {
            table_7_button.setSelected(false);
        }
        if (table_8_button.isSelected()) {
            table_8_button.setSelected(false);
        }
    }//GEN-LAST:event_table_4_buttonActionPerformed

    private void table_5_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_5_buttonActionPerformed
        // TODO add your handling code here:

        // Delselects all the other buttons, ensures only a single button is selected
        if (table_1_button.isSelected()) {
            table_1_button.setSelected(false);
        }
        if (table_2_button.isSelected()) {
            table_2_button.setSelected(false);
        }
        if (table_3_button.isSelected()) {
            table_3_button.setSelected(false);
        }
        if (table_4_button.isSelected()) {
            table_4_button.setSelected(false);
        }
        if (table_6_button.isSelected()) {
            table_6_button.setSelected(false);
        }
        if (table_7_button.isSelected()) {
            table_7_button.setSelected(false);
        }
        if (table_8_button.isSelected()) {
            table_8_button.setSelected(false);
        }
    }//GEN-LAST:event_table_5_buttonActionPerformed

    private void table_6_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_6_buttonActionPerformed
        // TODO add your handling code here:

        // Delselects all the other buttons, ensures only a single button is selected
        if (table_1_button.isSelected()) {
            table_1_button.setSelected(false);
        }
        if (table_2_button.isSelected()) {
            table_2_button.setSelected(false);
        }
        if (table_3_button.isSelected()) {
            table_3_button.setSelected(false);
        }
        if (table_4_button.isSelected()) {
            table_4_button.setSelected(false);
        }
        if (table_5_button.isSelected()) {
            table_5_button.setSelected(false);
        }
        if (table_7_button.isSelected()) {
            table_7_button.setSelected(false);
        }
        if (table_8_button.isSelected()) {
            table_8_button.setSelected(false);
        }
    }//GEN-LAST:event_table_6_buttonActionPerformed

    private void table_7_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_7_buttonActionPerformed
        // TODO add your handling code here:

        // Delselects all the other buttons, ensures only a single button is selected
        if (table_1_button.isSelected()) {
            table_1_button.setSelected(false);
        }
        if (table_2_button.isSelected()) {
            table_2_button.setSelected(false);
        }
        if (table_3_button.isSelected()) {
            table_3_button.setSelected(false);
        }
        if (table_4_button.isSelected()) {
            table_4_button.setSelected(false);
        }
        if (table_5_button.isSelected()) {
            table_5_button.setSelected(false);
        }
        if (table_6_button.isSelected()) {
            table_6_button.setSelected(false);
        }
        if (table_8_button.isSelected()) {
            table_8_button.setSelected(false);
        }
    }//GEN-LAST:event_table_7_buttonActionPerformed

    private void table_8_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_8_buttonActionPerformed
        // TODO add your handling code here:

        // Delselects all the other buttons, ensures only a single button is selected
        if (table_1_button.isSelected()) {
            table_1_button.setSelected(false);
        }
        if (table_2_button.isSelected()) {
            table_2_button.setSelected(false);
        }
        if (table_3_button.isSelected()) {
            table_3_button.setSelected(false);
        }
        if (table_4_button.isSelected()) {
            table_4_button.setSelected(false);
        }
        if (table_5_button.isSelected()) {
            table_5_button.setSelected(false);
        }
        if (table_6_button.isSelected()) {
            table_6_button.setSelected(false);
        }
        if (table_7_button.isSelected()) {
            table_7_button.setSelected(false);
        }
    }//GEN-LAST:event_table_8_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        RestaurantLayout rl = new RestaurantLayout();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detailPanel;
    private javax.swing.JLabel dirtyStatusLabel;
    private javax.swing.JPanel dirtyTablePanel;
    private javax.swing.JLabel freeStatusLabel;
    private javax.swing.JPanel freeTablePanel;
    private javax.swing.JLabel occupiedStatusLabel;
    private javax.swing.JLabel stdLabel;
    private javax.swing.JPanel stdPanel;
    private javax.swing.JLabel stdTableName;
    private javax.swing.JLabel tableStatusLabel;
    private javax.swing.JPanel tableStatusPanel;
    private javax.swing.JToggleButton table_1_button;
    private javax.swing.JToggleButton table_2_button;
    private javax.swing.JToggleButton table_3_button;
    private javax.swing.JToggleButton table_4_button;
    private javax.swing.JToggleButton table_5_button;
    private javax.swing.JToggleButton table_6_button;
    private javax.swing.JToggleButton table_7_button;
    private javax.swing.JToggleButton table_8_button;
    private javax.swing.JPanel tablesPanel;
    private javax.swing.JPanel usedTablePanel;
    // End of variables declaration//GEN-END:variables
}
