/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantautomation;

/**
 *
 * @author Alejandro
 */
public class EditEmployee extends javax.swing.JFrame {
    RestrauntDatabase rD;
    /**
     * Creates new form EditEmployee
     */
    public EditEmployee(RestrauntDatabase r) {
        rD = r;
        initComponents();
        addPanel.setVisible(false);
        refreshNames(rD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removePanel = new javax.swing.JPanel();
        editEmpLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empListTextArea = new javax.swing.JTextArea();
        refreshButton = new javax.swing.JButton();
        editLabel = new javax.swing.JLabel();
        editTextField = new javax.swing.JTextField();
        validateNameButton = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        newUsernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        empLevelLabel = new javax.swing.JLabel();
        empLevelComboBox = new javax.swing.JComboBox<>();
        getUNPWButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee - Edit");
        setPreferredSize(new java.awt.Dimension(400, 569));
        setResizable(false);

        removePanel.setBackground(new java.awt.Color(255, 255, 255));

        editEmpLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        editEmpLabel.setText("Edit Employee");

        empListTextArea.setEditable(false);
        empListTextArea.setColumns(20);
        empListTextArea.setFont(new java.awt.Font("Segoe WP Light", 0, 18)); // NOI18N
        empListTextArea.setRows(5);
        jScrollPane1.setViewportView(empListTextArea);

        refreshButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        editLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        editLabel.setText("Edit:");

        editTextField.setText("Enter First Name To Edit");
        editTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearText(evt);
            }
        });

        validateNameButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        validateNameButton.setText("Validate Name");
        validateNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateNameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removePanelLayout = new javax.swing.GroupLayout(removePanel);
        removePanel.setLayout(removePanelLayout);
        removePanelLayout.setHorizontalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addComponent(editEmpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addComponent(editLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editTextField))
                    .addComponent(validateNameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        removePanelLayout.setVerticalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmpLabel)
                    .addComponent(refreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(editTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validateNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addPanel.setBackground(new java.awt.Color(255, 255, 255));

        firstNameLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        firstNameLabel.setText("Frist Name");

        firstNameTextField.setBackground(new java.awt.Color(240, 240, 240));

        lastNameLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name");

        lastNameTextField.setBackground(new java.awt.Color(240, 240, 240));

        usernameLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        usernameLabel.setText("Username:");

        newUsernameLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        newUsernameLabel.setText(firstNameTextField.getText());

        passwordLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        passwordLabel.setText("Password:");

        newPasswordLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        newPasswordLabel.setText(lastNameTextField.getText());

        empLevelLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        empLevelLabel.setText("Employee Level");

        empLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Waiter" }));

        getUNPWButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        getUNPWButton.setText("Generate Username | Password");
        getUNPWButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getUNPWButtonActionPerformed(evt);
            }
        });

        confirmButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(lastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(getUNPWButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(usernameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(empLevelLabel)
                        .addGap(18, 18, 18)
                        .addComponent(empLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(newUsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(newPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empLevelLabel)
                    .addComponent(empLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(getUNPWButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(removePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refreshNames(rD);
    }//GEN-LAST:event_refreshButtonActionPerformed

    public void refreshNames(RestrauntDatabase rD) {
        String setEmpList = "";
        
        for (int i = 0; i < rD.getAllUsernames().size(); i++) {
            setEmpList += (rD.getEmployeeData(rD.getAllUsernames().get(i)).get(0) + 
                    " " + (rD.getEmployeeData(rD.getAllUsernames().get(i)).get(1)) +
                    " " + (rD.getEmployeeData(rD.getAllUsernames().get(i)).get(2)) + 
                    " " + (rD.getEmployeeData(rD.getAllUsernames().get(i)).get(3)) + 
                    " " + (rD.getEmployeeData(rD.getAllUsernames().get(i)).get(4)) + "\n");
        }
        
        empListTextArea.setText(setEmpList);
    }
    
    private void clearText(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearText
        // TODO add your handling code here:

        if (editTextField.getText().equals("Enter First Name To Edit")) {
            editTextField.setText("");
        }
        addPanel.setVisible(false);
    }//GEN-LAST:event_clearText

    private void validateNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateNameButtonActionPerformed
        // TODO add your handling code here:

        if (rD.isEmployee(editTextField.getText())) {
            rD.getEmployeeData(editTextField.getText()).get(0);
            addPanel.setVisible(true);
        } else {
            addPanel.setVisible(false);
        }
        
        firstNameTextField.setText(rD.getEmployeeData(editTextField.getText()).get(0));
        lastNameTextField.setText(rD.getEmployeeData(editTextField.getText()).get(1));
        confirmButton.setVisible(false);
        
        
    }//GEN-LAST:event_validateNameButtonActionPerformed

    private void getUNPWButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUNPWButtonActionPerformed
        // TODO add your handling code here:

        if (firstNameTextField.getText().equals("") && lastNameTextField.getText().equals("")) {
            confirmButton.setVisible(false);
        } else {
            confirmButton.setVisible(true);
            newUsernameLabel.setText(firstNameTextField.getText());
            newPasswordLabel.setText(lastNameTextField.getText());
        }

    }//GEN-LAST:event_getUNPWButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:

        int level = 0;
        if (empLevelComboBox.getSelectedItem().equals("Manager")) {
            level = 1;
        } else if (empLevelComboBox.getSelectedItem().equals("Waiter")) {
            level = 2;
        }

        rD.deleteEmployee(editTextField.getText());
        System.out.println("Removed: " + editTextField.getText());
        
        rD.insertEmployee(firstNameTextField.getText(), lastNameTextField.getText(), firstNameTextField.getText(), lastNameTextField.getText(), level);
        System.out.println("Added" + rD.getEmployeeData(firstNameTextField.getText()));
        this.setVisible(false);
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel editEmpLabel;
    private javax.swing.JLabel editLabel;
    private javax.swing.JTextField editTextField;
    private javax.swing.JComboBox<String> empLevelComboBox;
    private javax.swing.JLabel empLevelLabel;
    private javax.swing.JTextArea empListTextArea;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JButton getUNPWButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JLabel newUsernameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JPanel removePanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton validateNameButton;
    // End of variables declaration//GEN-END:variables
}
