/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantautomation;

import java.awt.Color;

/**
 *
 * @author Alejandro
 */
public class EditMenuItem extends javax.swing.JFrame {
    RestrauntDatabase rD;

    /**
     * Creates new form EditMenuItem
     */
    public EditMenuItem(RestrauntDatabase r) {
        rD = r;
        initComponents();
        addPanel.setVisible(false);
        refreshMenu(rD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removePanel = new javax.swing.JPanel();
        removeItemPanel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemListTextArea = new javax.swing.JTextArea();
        refreshButton = new javax.swing.JButton();
        removeLabel = new javax.swing.JLabel();
        removeTextField = new javax.swing.JTextField();
        validateNameButton = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        itemNameLabel = new javax.swing.JLabel();
        itemNameTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        validateItemButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        removePanel.setBackground(new java.awt.Color(255, 255, 255));

        removeItemPanel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        removeItemPanel.setText("Remove Item");

        itemListTextArea.setEditable(false);
        itemListTextArea.setColumns(20);
        itemListTextArea.setFont(new java.awt.Font("Segoe WP Light", 0, 18)); // NOI18N
        itemListTextArea.setRows(5);
        jScrollPane1.setViewportView(itemListTextArea);

        refreshButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        removeLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        removeLabel.setText("Edit");

        removeTextField.setText("Enter Item Name To Edit");
        removeTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearText(evt);
            }
        });

        validateNameButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        validateNameButton.setText("Validate Item Name");
        validateNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateNameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removePanelLayout = new javax.swing.GroupLayout(removePanel);
        removePanel.setLayout(removePanelLayout);
        removePanelLayout.setHorizontalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addComponent(removeItemPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addComponent(removeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeTextField))
                    .addComponent(validateNameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        removePanelLayout.setVerticalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(removeTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validateNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addPanel.setBackground(new java.awt.Color(255, 255, 255));

        cancelButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        itemNameLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        itemNameLabel.setText("Item Name");

        itemNameTextField.setBackground(new java.awt.Color(240, 240, 240));
        itemNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemNameTextFieldclearConfirm(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        priceLabel.setText("Price");

        priceTextField.setBackground(new java.awt.Color(240, 240, 240));
        priceTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priceTextFieldclearConfirm(evt);
            }
        });

        validateItemButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        validateItemButton.setText("Validate Item");
        validateItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateItemButtonActionPerformed(evt);
            }
        });

        confirmButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(validateItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(itemNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(priceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameLabel)
                    .addComponent(itemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(validateItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(removePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refreshMenu(rD);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void clearText(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearText
        // TODO add your handling code here:

        if (removeTextField.getText().equals("Enter Item Name To Remove")) {
            removeTextField.setText("");
        }

        addPanel.setVisible(false);
    }//GEN-LAST:event_clearText

    private void validateNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateNameButtonActionPerformed
        // TODO add your handling code here:

        if (rD.isMenuItem(removeTextField.getText())) {
            addPanel.setVisible(true);
            confirmButton.setVisible(false);
            itemNameTextField.setText(rD.getItemData(removeTextField.getText()).get(0));
            priceTextField.setText(rD.getItemData(removeTextField.getText()).get(1));
        } else {
            addPanel.setVisible(false);
        }
    }//GEN-LAST:event_validateNameButtonActionPerformed

    private void itemNameTextFieldclearConfirm(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemNameTextFieldclearConfirm
        // TODO add your handling code here:
        priceTextField.setForeground(Color.black);
        confirmButton.setVisible(false);

        if (priceTextField.getText().equals("Must Enter and Integer Value")) {
            priceTextField.setText("");
        }
    }//GEN-LAST:event_itemNameTextFieldclearConfirm

    private void priceTextFieldclearConfirm(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priceTextFieldclearConfirm
        // TODO add your handling code here:
        priceTextField.setForeground(Color.black);
        confirmButton.setVisible(false);

        if (priceTextField.getText().equals("Must Enter and Integer Value")) {
            priceTextField.setText("");
        }
    }//GEN-LAST:event_priceTextFieldclearConfirm

    private void validateItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateItemButtonActionPerformed
        // TODO add your handling code here:

        if (itemNameTextField.getText().equals("") && priceTextField.getText().equals("")) {

            confirmButton.setVisible(false);
        } else {

            if (isInt(priceTextField.getText())) {
                confirmButton.setVisible(true);
            } else {
                priceTextField.setForeground(Color.red);
                priceTextField.setText("Must Enter and Integer Value");
            }
        }
    }//GEN-LAST:event_validateItemButtonActionPerformed

    public boolean isInt(String s) {
        boolean isInt = false;
        
        for (int i = 0; i < s.length(); i++) {
            if (Character.isDigit(s.charAt(i))) {
                isInt = true;
            } else {
                isInt = false;
                return isInt;
            }
        }
        
        return isInt;
    }
    
    
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:

        rD.deleteItem(removeTextField.getText());
        rD.insertItem(itemNameTextField.getText(), Integer.parseInt(priceTextField.getText()));

        this.setVisible(false);
    }//GEN-LAST:event_confirmButtonActionPerformed

    
    public void refreshMenu(RestrauntDatabase rD) {
        
        String setMenuList = "";
        
        for (int i = 0; i < rD.getAllItems().size(); i++) {
            setMenuList += (rD.getItemData(rD.getAllItems().get(i)).get(0) + 
                    " " + rD.getItemData(rD.getAllItems().get(i)).get(1) +  "\n");
        }
        
        itemListTextArea.setText(setMenuList);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMenuItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMenuItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMenuItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMenuItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EditMenuItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextArea itemListTextArea;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JTextField itemNameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel removeItemPanel;
    private javax.swing.JLabel removeLabel;
    private javax.swing.JPanel removePanel;
    private javax.swing.JTextField removeTextField;
    private javax.swing.JButton validateItemButton;
    private javax.swing.JButton validateNameButton;
    // End of variables declaration//GEN-END:variables
}
