/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantautomation;

import java.util.ArrayList;

/**
 *
 * @author Alejandro
 */
public class Login extends javax.swing.JFrame {

    boolean login = false;
    RestrauntDatabase rd = new RestrauntDatabase ();
    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
        invalidText.setVisible(false);
    }
    
    public void deleteAllTables() {
        rd.deleteTable(1);
        rd.deleteTable(2);
        rd.deleteTable(3);
        rd.deleteTable(4);
        rd.deleteTable(5);
        rd.deleteTable(6);
        rd.deleteTable(7);
        rd.deleteTable(8);
    }
    
    public void addAllTables () {
        rd.insertItem("Clean", 1);
        rd.insertItem("Clean", 2);
        rd.insertItem("Clean", 3);
        rd.insertItem("Clean", 4);
        rd.insertItem("Clean", 5);
        rd.insertItem("Clean", 6);
        rd.insertItem("Clean", 7);
        rd.insertItem("Clean", 8);
    }
    
    public void addInitialMenu () {
        rd.insertItem("Hamburger", 4);
        rd.insertItem("Cheese Burger", 5);
        rd.insertItem("Baby Back Ribs", 20);
        rd.insertItem("BBQ Chicken", 8);
        rd.insertItem("Smoked Pork", 10);
        rd.insertItem("Chicken Sandwich", 7);
        rd.insertItem("Grilled Cheese", 4);
        rd.insertItem("BBQ Beef Ribs", 18);
        
        rd.insertItem("BBQ Chicken Salad", 8);
        rd.insertItem("Caesar Salad", 7);
        rd.insertItem("Salmon Salad", 9);
        
        rd.insertItem("Mac and Cheese", 3);
        rd.insertItem("Potato Salad", 3);
        rd.insertItem("Corn Bread", 3);
        rd.insertItem("Fries", 3);
        rd.insertItem("Cole Slaw", 3);
        rd.insertItem("Baked Beans", 3);
        
        rd.insertItem("Iced Tea", 3);
        rd.insertItem("Beer", 5);
        rd.insertItem("Water", 0);   
        rd.insertItem("Soft Drink", 4);
        rd.insertItem("Coffee", 2);
    }
    
    public void deleteAllMenu () {
        for (int i = 0; i < rd.getAllItems().size(); i = 0) {
            rd.deleteItem(rd.getAllItems().get(i));
        }
    }
    
    
    public void addInitialEmployees () {
        // FirstName, LastName, Username, Password, Rank
        // Manager = 1, Waiter = 2
        rd.insertEmployee("Sen", "Wang", "Sen", "Wang", 1);
        rd.insertEmployee("Alejandro", "Lemus", "Alejandro", "Lemus", 2);
        rd.insertEmployee("Jaylen", "Wimbish", "Jaylen", "Wimbish", 2);
        rd.insertEmployee("Michael", "Botsko", "Michael", "Botsko", 2);
    }
    
    public void deleteAllEmployees () {
        for (int i = 0; i < rd.getAllUsernames().size(); i = 0) {
            rd.deleteEmployee(rd.getAllUsernames().get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        unTextField = new javax.swing.JTextField();
        pwTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        invalidText = new javax.swing.JLabel();
        loginText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        unTextField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        unTextField.setForeground(new java.awt.Color(153, 153, 153));
        unTextField.setText("Username");
        unTextField.setBorder(null);
        unTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        unTextField.setMargin(new java.awt.Insets(2, 5, 2, 2));
        unTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearUsernameText(evt);
            }
        });

        pwTextField.setForeground(new java.awt.Color(153, 153, 153));
        pwTextField.setText("Password");
        pwTextField.setBorder(null);
        pwTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearPasswordText(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(204, 204, 204));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        invalidText.setForeground(new java.awt.Color(255, 102, 102));
        invalidText.setText("Invalid login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(invalidText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(pwTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        loginText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        loginText.setForeground(new java.awt.Color(153, 153, 153));
        loginText.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginText)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(loginText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String username =  unTextField.getText();
        String password =  pwTextField.getText();
        
        System.out.println(rd.getEmployeeData("Sen"));
        System.out.println(rd.getEmployeeData("Homer"));
        System.out.println(rd.getEmployeeData("Peter"));
        
        
        // Checks is username is in database
        if (rd.isEmployee(username)) {
            // Chaecks if the password of the database is related to the username
            if (password.equals(rd.getEmployeeData(username).get(3))) {
                this.login = true;
                
                invalidText.setVisible(false);
                
                // If the login is a manager load the manager window
                if (Integer.parseInt(rd.getEmployeeData(username).get(4)) == 1) {
                    System.out.println("Manager Login");
                    ManagerWindow mW = new ManagerWindow(rd);
                    mW.setVisible(true);
                } else if (Integer.parseInt(rd.getEmployeeData(username).get(4)) == 2) {
                    System.out.println("Waiter Login");
                    RestaurantLayout rL = new RestaurantLayout (rd);
                    rL.setVisible(true);
                }
            } else {
                invalidText.setText("Invalid Username - Password combination");
                invalidText.setVisible(true);
            }
            //setVisible(false);
            
        } else {
            invalidText.setText("Username not found");
            invalidText.setVisible(true);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void ClearUsernameText(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearUsernameText
        // TODO add your handling code here:
        if (unTextField.getText().equals("Username")) {
            unTextField.setText("");
        }
        
        if (pwTextField.getText().equals("")) {
            pwTextField.setText("Password");
        }
    }//GEN-LAST:event_ClearUsernameText

    private void clearPasswordText(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearPasswordText
        // TODO add your handling code here:
        if (pwTextField.getText().equals("Password")) {
            pwTextField.setText("");
        }
        
        if (unTextField.getText().equals("")) {
            unTextField.setText("Username");
        }
    }//GEN-LAST:event_clearPasswordText

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
        //below for running Webview Frame
        SwingFXWebView wframe = new SwingFXWebView();
        wframe.runWebBrowser();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel invalidText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginText;
    private javax.swing.JPasswordField pwTextField;
    private javax.swing.JTextField unTextField;
    // End of variables declaration//GEN-END:variables
}
